### PR TITLE
initial installs and Resources

### PR DESCRIPTION
**Pull request by nickMon85**

### CODE REVIEW

**Review by WalkerTexas-coder — DISMISSED** [review]
This looks good

**Review by WalkerTexas-coder — COMMENTED** [review]
Do you have rspec installed?

**Comment by nickMon85** [comment]
> Do you have rspec installed?
That was the first thing i did

**Review by WalkerTexas-coder — APPROVED** [review]
Nice!

**Comment by nickMon85** [comment]
> Nice!

Wait, Wait, can it go in twice, because I did it again just to make sure

**Pull request merged**
